local L = LibStub('AceLocale-3.0'):NewLocale('PetBattleScripts', 'frFR')
if not L then return end

--[[ L["ADDON_NAME"] = "Pet Battle Scripts" --]]
L["DATABASE_UPDATE_BASE_TO_FIRSTENEMY_NOTIFICATION"] = "J'ai constaté que vous aviez déjà utilisé la version modifiée de tdBattlePetScript et que certains scripts de la version modifiée du sélecteur de base avaient été migrés vers le sélecteur du premier ennemi"
L["DATABASE_UPDATED_TO"] = "Mettre à jour vers la version :"
L["DEFAULT_NEW_SCRIPT_NAME"] = "Nouveau script"
--[[ L["DIRECTOR_TEST_NEXT_ACTION"] = "Next action" --]]
L["EDITOR_CREATE_SCRIPT"] = "Créer un script"
L["EDITOR_EDIT_SCRIPT"] = "Modifier le script"
L["IN_BATTLE_DEBUGGING_SCRIPT"] = "Corriger un script"
--[[ L["IN_BATTLE_EXECUTE"] = "Autobattle" --]]
L["IN_BATTLE_NO_SCRIPT"] = "Aucun script"
L["IN_BATTLE_SELECT_SCRIPT"] = "Sélectionnez le script"
L["OPTION_AUTO_SELECT_SCRIPT_BY_ORDER"] = "Sélectionnez automatiquement les scripts en fonction de la priorité du sélecteur de script"
L["OPTION_AUTO_SELECT_SCRIPT_ONLY_ONE"] = "Sélectionner automatiquement lorsqu'il n'y a qu'un seul script"
L["OPTION_AUTOBUTTON_HOTKEY"] = "Raccourci du bouton automatique"
--[[ L["OPTION_AUTOBUTTON_HOTKEY_SECONDARY"] = "(secondary)" --]]
L["OPTION_EDITOR_FONT_FACE"] = "Police de caractères"
L["OPTION_EDITOR_FONT_SIZE"] = "Taille de la police de caractères"
L["OPTION_HIDE_MINIMAP"] = "Masquer l'icône de minimap"
L["OPTION_HIDE_SELECTOR_NO_SCRIPT"] = "Ne pas afficher le sélecteur de script lorsqu'il n'y a pas de script"
L["OPTION_LOCK_SCRIPT_SELECTOR"] = "Verrouiller le sélecteur de script"
L["OPTION_NO_WAIT_DELETE_SCRIPT"] = "Ne pas attendre lors de la suppression des scripts"
--[[ L["OPTION_NOTIFY_BUTTON_ACTIVE"] = "Play sound when \"Autobattle\" button becomes active" --]]
--[[ L["OPTION_NOTIFY_BUTTON_ACTIVE_SOUND"] = "Sound" --]]
L["OPTION_RESET_FRAMES"] = "Réinitialiser la taille et la position du panneau"
L["OPTION_SCRIPTSELECTOR_NOTES"] = "Ici, vous pouvez gérer si le sélecteur de script est activé et la priorité du sélecteur de script"
L["OPTION_SETTINGS_HIDE_MINIMAP_TOOLTIP"] = "La modification de ce paramètre nécessite le rechargement de l'interface utilisateur. Voulez-vous continuer ?"
L["OPTION_TEST_BREAK"] = "Débogage : la commande de test interrompt le script"
--[[ L["REMATCH_NOTE_SCRIPT_EXPORT_ADD_TO_NOTE_MENU_ITEM"] = "Add script to note" --]]
--[[ L["REMATCH_NOTE_SCRIPT_IMPORT_FAIL"] = [=[Importing at least one script from Rematch team notes failed:
%s]=] --]]
--[[ L["REMATCH_NOTE_SCRIPT_IMPORT_FAIL_EXIST_DIFFERENT"] = "A script already exists, and it is a different one. Delete note or script." --]]
--[[ L["REMATCH_NOTE_SCRIPT_IMPORT_FAIL_LINE"] = "- Team \"%s\": %s" --]]
--[[ L["REMATCH4_DEPRECATED"] = [=[Rematch 4 is old and support of the pet battle scripts addon for it will be dropped mid 2025. Please upgrade to Rematch 5.

Also, please notify us on Curseforge or GitHub, as we want to count whether a relevant number of users still use Rematch 4, contrary to our assumptions.]=] --]]
L["SCRIPT_EDITOR_AUTOFORMAT_SCRIPT"] = "Embellir le script"
L["SCRIPT_EDITOR_DELETE_SCRIPT_CONFIRMATION"] = "Êtes-vous sûr de vouloir supprimer le script [% s-% s] ?"
L["SCRIPT_EDITOR_FOUND_ERROR"] = "Erreur trouvée"
L["SCRIPT_EDITOR_LABEL_TOGGLE_EXTRA"] = "Basculer l'éditeur d'informations étendu"
L["SCRIPT_EDITOR_NAME_TITLE"] = "Nom du script"
L["SCRIPT_EDITOR_RUN_BUTTON"] = "fonctionne"
L["SCRIPT_EDITOR_SAVE_SUCCESS"] = "Enregistré avec succès"
L["SCRIPT_EDITOR_TEXTAREA_TITLE"] = "script"
L["SCRIPT_EDITOR_TITLE"] = "Éditeur de script"
L["SCRIPT_MANAGER_TITLE"] = "Gestionnaire de scripts"
L["SCRIPT_MANAGER_TOGGLE"] = "Activer ou désactiver le gestionnaire de scripts"
L["SCRIPT_SELECTOR_TITLE"] = "Sélecteur de script"
L["SCRIPT_SELECTOR_TOGGLE"] = "Active ou désactive le sélecteur de script"
L["SELECTOR_ALLINONE_NOTES"] = "Tous les combats de mascottes peuvent utiliser ce script"
L["SELECTOR_ALLINONE_TITLE"] = "Tout en un"
L["SELECTOR_BASE_ALLY"] = "Notre équipe"
L["SELECTOR_BASE_ENEMY"] = "Équipe ennemie"
L["SELECTOR_BASE_NOTES"] = "Ce sélecteur de script lie le script à la gamme complète des adversaires"
--[[ L["SELECTOR_BASE_TITLE"] = "Base" --]]
L["SELECTOR_FIRSTENEMY_NOTES"] = "Ce sélecteur de script lie le script au premier ennemi de la bataille"
L["SELECTOR_FIRSTENEMY_TITLE"] = "Premier ennemi"
L["SELECTOR_REMATCH_4_TO_5_UPDATE_NOTE"] = "Vous avez mis à jour Rematch 4 vers Rematch 5. Veuillez vérifier que vos scripts sont toujours correctement liés à vos équipes.\\nSi jamais la mise à jour a échoué, vous pouvez restaurer une sauvegarde de wow/WTF/Account/<account>/SavedVariables/tdBattlePetScript.lua, ou l'ouvrir et rechercher le texte \"Rematch\" et le retirer ou remplacer par \"Rematch5\", puis rechercher \"Rematch4\" et le replacer par \"Rematch\". Puis, revenez à la version Rematch 4 et signalez le bug sur https://github.com/axc450/pbs/issues/new en fournissant vos fichiers de variables sauvegardés pour Rematch et cet addon."
L["SELECTOR_REMATCH_4_TO_5_UPDATE_ORPHAN"] = "Un script nommé \"%s\" a été trouvé, lié à une équipe Rematch introuvable d'id \"%s\".\\nCela peut être dû à une erreur lors de la mise à jour de la base de données, ou à une corruption antérieure de données. Si cette erreur se produit pour un grand nombre de vos équipes, merci de le signaler en tant que bug. Sinon, vous pouvez supprimer les équipes orphelines dans le gestionnaire de script et les lier à nouveau à la bonne équipe."
L["SELECTOR_REMATCH_CANT_FORMAT_TOOLTIP_REMATCH_NOT_LOADED"] = "Information non disponible : l'addon Rematch n'est pas chargé."
--[[ L["SELECTOR_REMATCH_NO_TEAM_FOR_SCRIPT"] = "No team matches this script" --]]
--[[ L["SELECTOR_REMATCH_NOTES"] = "This script selector will be bound to the Rematch team." --]]
--[[ L["SELECTOR_REMATCH_TEAM_FORMAT"] = "Team: %s" --]]
--[[ L["SELECTOR_REMATCH_TITLE"] = "Rematch" --]]
L["SHARE_EXPORT_SCRIPT"] = "Exporter"
L["SHARE_IMPORT_CHOOSE_KEY"] = "Sélectionner la touche d'importation"
L["SHARE_IMPORT_CHOOSE_SELECTOR"] = "Sélectionner le plugin d'importation"
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_CHECKBOX"] = "Écraser et continuer l'importation"
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_WARNING"] = "Un script existe déjà, la poursuite de l'importation écrasera le script actuel."
L["SHARE_IMPORT_LABEL_HAS_EXTRA"] = "Ce texte d'import va charger des données supplémentaires en plus du script, en fonction du plugin. En général, il s'agira d'informations concernant l'équipe correspondante."
L["SHARE_IMPORT_PLUGIN_NOT_ENABLED"] = "Import impossible : le plugin n'est pas activé."
L["SHARE_IMPORT_REINPUT_TEXT"] = "Rééditer"
L["SHARE_IMPORT_SCRIPT"] = "Importer"
L["SHARE_IMPORT_SCRIPT_EXISTS"] = "Le script existe déjà"
L["SHARE_IMPORT_SCRIPT_NOT_IMPORT_STRING_WARNING"] = "Vous avez saisi le script, il est recommandé d'utiliser le code de partage pour importer, bien sûr, vous pouvez continuer à importer"
L["SHARE_IMPORT_SCRIPT_WELCOME"] = "Copiez le script partagé dans la zone de saisie"
L["SHARE_IMPORT_STRING_INCOMPLETE"] = "Les données du script partagé sont incomplètes. Mais il peut toujours être importé."
L["TOOLTIP_CREATE_OR_DEBUG_SCRIPT"] = "Créer ou déboguer un script"
