L = L or {}
L["SCRIPT_EDITOR_AUTOFORMAT_SCRIPT"] = "Skript formatieren" -- WAS: Beauty script
L["EDITOR_CREATE_SCRIPT"] = "Skript erstellen" -- WAS: Create script
L["IN_BATTLE_DEBUGGING_SCRIPT"] = "Skript debuggen" -- WAS: Debugging script
-- DELETE: DIALOG_COPY_URL_HELP = Drücke STRG+C, um es zu kopieren und im Browser zu öffnen
-- DELETE: Don't ask me = Ignorieren
-- DELETE: Download = Herunterladen
L["EDITOR_EDIT_SCRIPT"] = "Skript bearbeiten" -- WAS: Edit script
L["SHARE_EXPORT_SCRIPT"] = "Exportieren" -- WAS: Export
L["OPTION_EDITOR_FONT_FACE"] = "Schriftart" -- WAS: Font face
L["OPTION_EDITOR_FONT_SIZE"] = "Schriftgröße" -- WAS: Font size
L["SCRIPT_EDITOR_FOUND_ERROR"] = "Fehler gefunden" -- WAS: Found error
L["SHARE_IMPORT_SCRIPT"] = "Importieren" -- WAS: Import
L["SHARE_IMPORT_CHOOSE_KEY"] = "Wert auswählen..." -- WAS: IMPORT_CHOOSE_KEY
L["SHARE_IMPORT_CHOOSE_SELECTOR"] = "Skript-Selektor auswählen..." -- WAS: IMPORT_CHOOSE_PLUGIN
L["SHARE_IMPORT_REINPUT_TEXT"] = "Erneut bearbeiten" -- WAS: IMPORT_REINPUT_TEXT
L["SHARE_IMPORT_SCRIPT_EXISTS"] = "Skript bereits vorhanden" -- WAS: IMPORT_SCRIPT_EXISTS
L["SHARE_IMPORT_SCRIPT_NOT_IMPORT_STRING_WARNING"] = "Es wird empfohlen, den Import mit einem gültigen Share-String anstelle eines manuell eingegebenen Skripts durchzuführen. Dennoch fortfahren?" -- WAS: IMPORT_SCRIPT_WARNING
L["SHARE_IMPORT_SCRIPT_WELCOME"] = "Füge Share-String oder Skript in das Eingabefeld ein." -- WAS: IMPORT_SCRIPT_WELCOME
L["SHARE_IMPORT_STRING_INCOMPLETE"] = "Die Daten des Share-Strings sind zwar unvollständig, aber können trotzdem importiert werden." -- WAS: IMPORT_SHARED_STRING_WARNING
-- DELETE: Installed = Installiert
L["DEFAULT_NEW_SCRIPT_NAME"] = "Neues Skript" -- WAS: New script
L["DIRECTOR_TEST_NEXT_ACTION"] = "Nächste Aktion" -- WAS: NEXT_ACTION
L["IN_BATTLE_NO_SCRIPT"] = "Kein Skript" -- WAS: No script
L["SELECTOR_REMATCH_NO_TEAM_FOR_SCRIPT"] = "Kein Team passt zu diesem Skript" -- WAS: NO_TEAM_FOR_SCRIPT
-- DELETE: Not Installed = Nicht installiert
L["SELECTOR_REMATCH_NOTES"] = "Dieser Skript-Selektor gilt basiered auf dem aktuellen Rematch Team." -- WAS: NOTES
-- DELETE: OPTION_GENERAL_NOTES = Hier findest du einige allgemeine Einstellungen.
-- DELETE: OPTION_SCRIPTEDITOR_NOTES = Hier findest du Einstellungen für den Skript-Editor.
L["OPTION_SCRIPTSELECTOR_NOTES"] = "Hier kannst du die Verfügbarkeit und Priorität der Skript-Selektoren einstellen."
L["OPTION_AUTO_SELECT_SCRIPT_BY_ORDER"] = "Skripte automatisch auf Basis der Skript-Selektor-Prioritäten auswählen" -- WAS: OPTION_SETTINGS_AUTO_SELECT_SCRIPT_BY_ORDER
L["OPTION_AUTO_SELECT_SCRIPT_ONLY_ONE"] = "Automatisch nur ein Skript auswählen" -- WAS: OPTION_SETTINGS_AUTO_SELECT_SCRIPT_ONLY_ONE
L["OPTION_AUTOBUTTON_HOTKEY"] = "Hotkey für die Auto-Schaltfläche" -- WAS: OPTION_SETTINGS_AUTOBUTTON_HOTKEY
L["OPTION_HIDE_MINIMAP"] = "Minimap-Symbol verstecken" -- WAS: OPTION_SETTINGS_HIDE_MINIMAP
L["OPTION_SETTINGS_HIDE_MINIMAP_TOOLTIP"] = "Um diese Einstellung zu ändern, muss die Benutzeroberfläche neu geladen werden. Willst du fortfahren?"
L["OPTION_HIDE_SELECTOR_NO_SCRIPT"] = "Skript-Selektor nicht anzeigen, wenn keine Skripte verfügbar sind" -- WAS: OPTION_SETTINGS_HIDE_SELECTOR_NO_SCRIPT
L["OPTION_LOCK_SCRIPT_SELECTOR"] = "Skript-Selektor sperren (kann nicht verschoben werden)" -- WAS: OPTION_SETTINGS_LOCK_SCRIPT_SELECTOR
L["OPTION_NO_WAIT_DELETE_SCRIPT"] = "Nicht auf das Löschen eines Skripts warten" -- WAS: OPTION_SETTINGS_NO_WAIT_DELETE_SCRIPT
L["OPTION_NOTIFY_BUTTON_ACTIVE"] = "Spiele Ton wenn \"Autobattle\" Schaltfläche aktiv wird" -- WAS: OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE
L["OPTION_NOTIFY_BUTTON_ACTIVE_SOUND"] = "Ton" -- WAS: OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE_SOUND
L["OPTION_RESET_FRAMES"] = "Größe und Position von allen Fenstern zurücksetzen" -- WAS: OPTION_SETTINGS_RESET_FRAMES
L["OPTION_TEST_BREAK"] = "Entwickler: Die 'test' Aktion unterbricht die Ausführung" -- WAS: OPTION_SETTINGS_TEST_BREAK
-- DELETE: Options = Optionen
L["SELECTOR_ALLINONE_NOTES"] = "Dieses Skript kann in allen Haustierkämpfen verwendet werden." -- WAS: PLUGINALLINONE_NOTES
L["SELECTOR_ALLINONE_TITLE"] = "Alle in einem" -- WAS: PLUGINALLINONE_TITLE
L["SELECTOR_BASE_NOTES"] = "Dieser Skript-Selektor gilt für Verbündeten und Feind." -- WAS: PLUGINBASE_NOTES
L["SELECTOR_BASE_ALLY"] = "Verbündeter" -- WAS: PLUGINBASE_TEAM_ALLY
L["SELECTOR_BASE_ENEMY"] = "Feind" -- WAS: PLUGINBASE_TEAM_ENEMY
L["SELECTOR_BASE_TITLE"] = "Basis" -- WAS: PLUGINBASE_TITLE
-- DELETE: PLUGINBASE_TOOLTIP_CREATE_SCRIPT = Basis: Ein Skript für das aktuelle Match erstellen
L["SELECTOR_FIRSTENEMY_NOTES"] = "Dieser Skript-Selektor gilt für den ersten Gegner des Kampfes." -- WAS: PLUGINFIRSTENEMY_NOTES
L["DATABASE_UPDATE_BASE_TO_FIRSTENEMY_NOTIFICATION"] = "Es wurde festgestellt, dass du zuvor eine modifizierte Version von tdBattlePetScript verwendet hast und einige Skripte des modifizierten Basis-Selektors in den Erster Gegner-Selektor migriert hast." -- WAS: PLUGINFIRSTENEMY_NOTIFY
L["SELECTOR_FIRSTENEMY_TITLE"] = "Erster Gegner" -- WAS: PLUGINFIRSTENEMY_TITLE
L["SCRIPT_EDITOR_RUN_BUTTON"] = "Ausführen" -- WAS: Run
L["SCRIPT_EDITOR_SAVE_SUCCESS"] = "Erfolgreich gespeichert" -- WAS: Save success
L["SCRIPT_EDITOR_TEXTAREA_TITLE"] = "Skript" -- WAS: Script
-- DELETE: Script author = Skript-Ersteller
L["SCRIPT_EDITOR_TITLE"] = "Skript-Editor" -- WAS: Script editor
L["SCRIPT_MANAGER_TITLE"] = "Skript-Manager" -- WAS: Script manager
L["SCRIPT_EDITOR_NAME_TITLE"] = "Skriptname" -- WAS: Script name
-- DELETE: Script notes = Anmerkungen zum Skript
L["SCRIPT_SELECTOR_TITLE"] = "Skript-Selektor" -- WAS: Script selector
L["SCRIPT_EDITOR_DELETE_SCRIPT_CONFIRMATION"] = "Bist du sicher, dass du das Skript |cffffd000[%s - %s]|r |cffff0000löschen|r willst?" -- WAS: SCRIPT_EDITOR_DELETE_SCRIPT
L["SCRIPT_EDITOR_LABEL_TOGGLE_EXTRA"] = "Plugin-Daten-Editor öffnen/schließen"
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_WARNING"] = "Das Skript existiert bereits mit diesen Einstellungen. Wenn du mit der Importierung fortfährst, wird das aktuelle Skript überschrieben." -- WAS: SCRIPT_IMPORT_LABEL_COVER
L["SHARE_IMPORT_LABEL_EXTRA"] = "Mit dem Importieren der Plugin-Daten fortfahren" -- WAS: SCRIPT_IMPORT_LABEL_EXTRA
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_CHECKBOX"] = "Überschreiben und Importieren fortsetzen" -- WAS: SCRIPT_IMPORT_LABEL_GOON
-- DELETE: SCRIPT_SELECTOR_LOST_TOOLTIP = Skript-Selektor-Entwickler definiert nicht die OnTooltipFormatting-Funktion
-- DELETE: SCRIPT_SELECTOR_NOT_MATCH = Kein Skript-Selektor stimmt mit dem aktuellen Match überein
-- DELETE: SCRIPT_SELECTOR_NOTINSTALLED_HELP = Linksklick zum Anschauen, Rechtsklick zum Schließen
-- DELETE: SCRIPT_SELECTOR_NOTINSTALLED_TEXT = Kein geeigneter Skript-Selektor installiert!
L["IN_BATTLE_SELECT_SCRIPT"] = "Skript auswählen" -- WAS: Select script
L["SCRIPT_MANAGER_TOGGLE"] = "Skript-Manager öffnen/schließen" -- WAS: TOGGLE_SCRIPT_MANAGER
L["SCRIPT_SELECTOR_TOGGLE"] = "Skript-Selektor öffnen/schließen" -- WAS: TOGGLE_SCRIPT_SELECTOR
L["TOOLTIP_CREATE_OR_DEBUG_SCRIPT"] = "Ein Skript erstellen oder debuggen"
L["DATABASE_UPDATED_TO"] = "Aktualisiert auf Version: " -- WAS: UPDATED
-- DELETE: WRITE_SCRIPT = Skript schreiben
