L = L or {}
L["ADDON_NAME"] = "Pet Battle Scripts"
L["IN_BATTLE_EXECUTE"] = "Autobattle" -- WAS: Auto
L["SCRIPT_EDITOR_AUTOFORMAT_SCRIPT"] = "Format script" -- WAS: Beauty script
L["EDITOR_CREATE_SCRIPT"] = "Create script" -- WAS: Create script
L["IN_BATTLE_DEBUGGING_SCRIPT"] = "Debugging script" -- WAS: Debugging script
-- DELETE: DIALOG_COPY_URL_HELP = Press ctrl-c to copy and open it in the browser
-- DELETE: Don't ask me = Don't ask me
-- DELETE: Download = Download
L["EDITOR_EDIT_SCRIPT"] = "Edit script" -- WAS: Edit script
L["SHARE_EXPORT_SCRIPT"] = "Export" -- WAS: Export
L["OPTION_EDITOR_FONT_FACE"] = "Font face" -- WAS: Font face
L["OPTION_EDITOR_FONT_SIZE"] = "Font size" -- WAS: Font size
L["SCRIPT_EDITOR_FOUND_ERROR"] = "Found error" -- WAS: Found error
L["SHARE_IMPORT_SCRIPT"] = "Import" -- WAS: Import
L["SHARE_IMPORT_CHOOSE_KEY"] = "Select the key..." -- WAS: IMPORT_CHOOSE_KEY
L["SHARE_IMPORT_CHOOSE_SELECTOR"] = "Select the script selector..." -- WAS: IMPORT_CHOOSE_PLUGIN
L["SHARE_IMPORT_REINPUT_TEXT"] = "Re-edit" -- WAS: IMPORT_REINPUT_TEXT
L["SHARE_IMPORT_SCRIPT_EXISTS"] = "Script exists" -- WAS: IMPORT_SCRIPT_EXISTS
L["SHARE_IMPORT_SCRIPT_NOT_IMPORT_STRING_WARNING"] = "You have entered the script and are advised to import using the Share string, although you can continue to import as well." -- WAS: IMPORT_SCRIPT_WARNING
L["SHARE_IMPORT_SCRIPT_WELCOME"] = "Copy Share string or script to edit box." -- WAS: IMPORT_SCRIPT_WELCOME
L["SHARE_IMPORT_STRING_INCOMPLETE"] = "Share string data incomplete. But you can still import it." -- WAS: IMPORT_SHARED_STRING_WARNING
-- DELETE: Installed = Installed
L["DEFAULT_NEW_SCRIPT_NAME"] = "New script" -- WAS: New script
L["DIRECTOR_TEST_NEXT_ACTION"] = "Next action" -- WAS: NEXT_ACTION
L["IN_BATTLE_NO_SCRIPT"] = "No script" -- WAS: No script
L["SELECTOR_REMATCH_NO_TEAM_FOR_SCRIPT"] = "No team matches this script" -- WAS: NO_TEAM_FOR_SCRIPT
-- DELETE: Not Installed = Not Installed
L["SELECTOR_REMATCH_NOTES"] = "This script selector will be bound to the Rematch team." -- WAS: NOTES
-- DELETE: OPTION_GENERAL_NOTES = Here are some general Settings.
-- DELETE: OPTION_SCRIPTEDITOR_NOTES = Here is the script editor preferences
L["OPTION_SCRIPTSELECTOR_NOTES"] = "Here you can manage the script selector is open, and its priority."
L["OPTION_AUTO_SELECT_SCRIPT_BY_ORDER"] = "Automatically select script by script selector order" -- WAS: OPTION_SETTINGS_AUTO_SELECT_SCRIPT_BY_ORDER
L["OPTION_AUTO_SELECT_SCRIPT_ONLY_ONE"] = "Automatically select script by script selector priority" -- WAS: OPTION_SETTINGS_AUTO_SELECT_SCRIPT_ONLY_ONE
L["OPTION_AUTOBUTTON_HOTKEY"] = "Autobattle Hotkey" -- WAS: OPTION_SETTINGS_AUTOBUTTON_HOTKEY
L["OPTION_HIDE_MINIMAP"] = "Hide minimap icon" -- WAS: OPTION_SETTINGS_HIDE_MINIMAP
L["OPTION_SETTINGS_HIDE_MINIMAP_TOOLTIP"] = "Changing this setting requires reloading the UI. Do you want to continue?"
L["OPTION_HIDE_SELECTOR_NO_SCRIPT"] = "The script selector is not displayed when there is no script" -- WAS: OPTION_SETTINGS_HIDE_SELECTOR_NO_SCRIPT
L["OPTION_LOCK_SCRIPT_SELECTOR"] = "Lock the script selector" -- WAS: OPTION_SETTINGS_LOCK_SCRIPT_SELECTOR
L["OPTION_NO_WAIT_DELETE_SCRIPT"] = "Do not wait for the script to be deleted" -- WAS: OPTION_SETTINGS_NO_WAIT_DELETE_SCRIPT
L["OPTION_NOTIFY_BUTTON_ACTIVE"] = "Play sound when \"Autobattle\" button becomes active" -- WAS: OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE
L["OPTION_NOTIFY_BUTTON_ACTIVE_SOUND"] = "Sound" -- WAS: OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE_SOUND
L["OPTION_RESET_FRAMES"] = "Reset the panel size and position" -- WAS: OPTION_SETTINGS_RESET_FRAMES
L["OPTION_TEST_BREAK"] = "Let 'test' action stop script" -- WAS: OPTION_SETTINGS_TEST_BREAK
-- DELETE: Options = Options
L["SELECTOR_ALLINONE_NOTES"] = "This script can be used in all pet battles." -- WAS: PLUGINALLINONE_NOTES
L["SELECTOR_ALLINONE_TITLE"] = "All in one" -- WAS: PLUGINALLINONE_TITLE
L["SELECTOR_BASE_NOTES"] = "This script selector matches ally and enemy." -- WAS: PLUGINBASE_NOTES
L["SELECTOR_BASE_ALLY"] = "Ally" -- WAS: PLUGINBASE_TEAM_ALLY
L["SELECTOR_BASE_ENEMY"] = "Enemy" -- WAS: PLUGINBASE_TEAM_ENEMY
L["SELECTOR_BASE_TITLE"] = "Base" -- WAS: PLUGINBASE_TITLE
-- DELETE: PLUGINBASE_TOOLTIP_CREATE_SCRIPT = Base: Create a script for the current match
L["SELECTOR_FIRSTENEMY_NOTES"] = "This script selector binds the script to the first enemy in the battle." -- WAS: PLUGINFIRSTENEMY_NOTES
L["DATABASE_UPDATE_BASE_TO_FIRSTENEMY_NOTIFICATION"] = "Discover that you've previously used the modified version of tdBattlePetScript and have migrated some of the scripts for the modified Base Selector to firstEnemy Selector." -- WAS: PLUGINFIRSTENEMY_NOTIFY
L["SELECTOR_FIRSTENEMY_TITLE"] = "First enemy" -- WAS: PLUGINFIRSTENEMY_TITLE
L["SCRIPT_EDITOR_RUN_BUTTON"] = "Run" -- WAS: Run
L["SCRIPT_EDITOR_SAVE_SUCCESS"] = "Save success" -- WAS: Save success
L["SCRIPT_EDITOR_TEXTAREA_TITLE"] = "Script" -- WAS: Script
-- DELETE: Script author = Script author
L["SCRIPT_EDITOR_TITLE"] = "Script editor" -- WAS: Script editor
L["SCRIPT_MANAGER_TITLE"] = "Script manager" -- WAS: Script manager
L["SCRIPT_EDITOR_NAME_TITLE"] = "Script name" -- WAS: Script name
-- DELETE: Script notes = Script notes
L["SCRIPT_SELECTOR_TITLE"] = "Script selector" -- WAS: Script selector
L["SCRIPT_EDITOR_DELETE_SCRIPT_CONFIRMATION"] = "Are you sure you want to |cffff0000delete|r the script |cffffd000[%s - %s]|r ?" -- WAS: SCRIPT_EDITOR_DELETE_SCRIPT
L["SCRIPT_EDITOR_LABEL_TOGGLE_EXTRA"] = "Toggle extension information editor"
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_WARNING"] = "The matching mode existing script, and continue to import will cover the current script." -- WAS: SCRIPT_IMPORT_LABEL_COVER
L["SHARE_IMPORT_LABEL_EXTRA"] = "Continue to import the plugin data" -- WAS: SCRIPT_IMPORT_LABEL_EXTRA
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_CHECKBOX"] = "Cover and continue to import" -- WAS: SCRIPT_IMPORT_LABEL_GOON
-- DELETE: SCRIPT_SELECTOR_LOST_TOOLTIP = Script selector developer does not define the function `OnTooltipFormatting`
-- DELETE: SCRIPT_SELECTOR_NOT_MATCH = No script selector matches to the current battle
-- DELETE: SCRIPT_SELECTOR_NOTINSTALLED_HELP = Left click to view, right click to close
-- DELETE: SCRIPT_SELECTOR_NOTINSTALLED_TEXT = A useful script selector is not installed!
L["IN_BATTLE_SELECT_SCRIPT"] = "Select script" -- WAS: Select script
L["SELECTOR_REMATCH_TEAM_FORMAT"] = "Team:  %s" -- WAS: TEAM
L["SELECTOR_REMATCH_TITLE"] = "Rematch" -- WAS: TITLE
L["SCRIPT_MANAGER_TOGGLE"] = "Toggle script manager" -- WAS: TOGGLE_SCRIPT_MANAGER
L["SCRIPT_SELECTOR_TOGGLE"] = "Toggle script selector" -- WAS: TOGGLE_SCRIPT_SELECTOR
L["TOOLTIP_CREATE_OR_DEBUG_SCRIPT"] = "Create or debug script"
L["DATABASE_UPDATED_TO"] = "Addon updated to" -- WAS: UPDATED
-- DELETE: WRITE_SCRIPT = Write script
