L = L or {}
L["SCRIPT_EDITOR_AUTOFORMAT_SCRIPT"] = "Embellir le script" -- WAS: Beauty script
L["EDITOR_CREATE_SCRIPT"] = "Créer un script" -- WAS: Create script
L["IN_BATTLE_DEBUGGING_SCRIPT"] = "Corriger un script" -- WAS: Debugging script
-- DELETE: DIALOG_COPY_URL_HELP = Appuyer sur CTRL+C pour copier l'adresse
-- DELETE: Don't ask me = Ne pas me demander
-- DELETE: Download = Télécharger
L["EDITOR_EDIT_SCRIPT"] = "Modifier le script" -- WAS: Edit script
L["SHARE_EXPORT_SCRIPT"] = "Exporter" -- WAS: Export
L["OPTION_EDITOR_FONT_FACE"] = "Police de caractère" -- WAS: Font face
L["OPTION_EDITOR_FONT_SIZE"] = "Taille de la police de caractère" -- WAS: Font size
L["SCRIPT_EDITOR_FOUND_ERROR"] = "Erreur trouvée" -- WAS: Found error
L["SHARE_IMPORT_SCRIPT"] = "Importer" -- WAS: Import
L["SHARE_IMPORT_CHOOSE_KEY"] = "Sélectionner la touche d'importation" -- WAS: IMPORT_CHOOSE_KEY
L["SHARE_IMPORT_CHOOSE_SELECTOR"] = "Sélectionner le plugin d'importation" -- WAS: IMPORT_CHOOSE_PLUGIN
L["SHARE_IMPORT_REINPUT_TEXT"] = "Rééditer" -- WAS: IMPORT_REINPUT_TEXT
L["SHARE_IMPORT_SCRIPT_EXISTS"] = "Le script existe déjà" -- WAS: IMPORT_SCRIPT_EXISTS
L["SHARE_IMPORT_SCRIPT_NOT_IMPORT_STRING_WARNING"] = "Vous avez saisi le script, il est recommandé d'utiliser le code de partage pour importer, bien sûr, vous pouvez continuer à importer" -- WAS: IMPORT_SCRIPT_WARNING
L["SHARE_IMPORT_SCRIPT_WELCOME"] = "Copiez le script partagé dans la zone de saisie" -- WAS: IMPORT_SCRIPT_WELCOME
L["SHARE_IMPORT_STRING_INCOMPLETE"] = "Les données du script partagé sont incomplètes. Mais il peut toujours être importé." -- WAS: IMPORT_SHARED_STRING_WARNING
-- DELETE: Installed = installé
L["DEFAULT_NEW_SCRIPT_NAME"] = "Nouveau script" -- WAS: New script
L["IN_BATTLE_NO_SCRIPT"] = "Aucun script" -- WAS: No script
-- DELETE: Not Installed = Pas installé
-- DELETE: OPTION_GENERAL_NOTES = Paramètres généraux
-- DELETE: OPTION_SCRIPTEDITOR_NOTES = Paramètres de l'éditeur de script
L["OPTION_SCRIPTSELECTOR_NOTES"] = "Ici, vous pouvez gérer si le sélecteur de script est activé et la priorité du sélecteur de script"
L["OPTION_AUTO_SELECT_SCRIPT_BY_ORDER"] = "Sélectionnez automatiquement les scripts en fonction de la priorité du sélecteur de script" -- WAS: OPTION_SETTINGS_AUTO_SELECT_SCRIPT_BY_ORDER
L["OPTION_AUTO_SELECT_SCRIPT_ONLY_ONE"] = "Sélectionner automatiquement lorsqu'il n'y a qu'un seul script" -- WAS: OPTION_SETTINGS_AUTO_SELECT_SCRIPT_ONLY_ONE
L["OPTION_AUTOBUTTON_HOTKEY"] = "Raccourci du bouton automatique" -- WAS: OPTION_SETTINGS_AUTOBUTTON_HOTKEY
L["OPTION_HIDE_MINIMAP"] = "Masquer l'icône de minimap" -- WAS: OPTION_SETTINGS_HIDE_MINIMAP
L["OPTION_SETTINGS_HIDE_MINIMAP_TOOLTIP"] = "La modification de ce paramètre nécessite le rechargement de l'interface utilisateur. Voulez-vous continuer?"
L["OPTION_HIDE_SELECTOR_NO_SCRIPT"] = "Ne pas afficher le sélecteur de script lorsqu'il n'y a pas de script" -- WAS: OPTION_SETTINGS_HIDE_SELECTOR_NO_SCRIPT
L["OPTION_LOCK_SCRIPT_SELECTOR"] = "Verrouiller le sélecteur de script" -- WAS: OPTION_SETTINGS_LOCK_SCRIPT_SELECTOR
L["OPTION_NO_WAIT_DELETE_SCRIPT"] = "Ne pas attendre lors de la suppression des scripts" -- WAS: OPTION_SETTINGS_NO_WAIT_DELETE_SCRIPT
L["OPTION_RESET_FRAMES"] = "Réinitialiser la taille et la position du panneau" -- WAS: OPTION_SETTINGS_RESET_FRAMES
L["OPTION_TEST_BREAK"] = "Débogage: la commande de test interrompt le script" -- WAS: OPTION_SETTINGS_TEST_BREAK
-- DELETE: Options = Installer
L["SELECTOR_ALLINONE_NOTES"] = "Tous les combat de mascotes peuvent utiliser ce script" -- WAS: PLUGINALLINONE_NOTES
L["SELECTOR_ALLINONE_TITLE"] = "Tout en un" -- WAS: PLUGINALLINONE_TITLE
L["SELECTOR_BASE_NOTES"] = "Ce sélecteur de script lie le script à la gamme complète des adversaires" -- WAS: PLUGINBASE_NOTES
L["SELECTOR_BASE_ALLY"] = "Notre équipe" -- WAS: PLUGINBASE_TEAM_ALLY
L["SELECTOR_BASE_ENEMY"] = "Équipe ennemie" -- WAS: PLUGINBASE_TEAM_ENEMY
L["SELECTOR_BASE_TITLE"] = "基础" -- WAS: PLUGINBASE_TITLE
-- DELETE: PLUGINBASE_TOOLTIP_CREATE_SCRIPT = Bases: créer un script pour le match en cours
L["SELECTOR_FIRSTENEMY_NOTES"] = "Ce sélecteur de script lie le script au premier ennemi de la bataille" -- WAS: PLUGINFIRSTENEMY_NOTES
L["DATABASE_UPDATE_BASE_TO_FIRSTENEMY_NOTIFICATION"] = "J'ai constaté que vous aviez déjà utilisé la version modifiée de tdBattlePetScript et que certains scripts de la version modifiée du sélecteur de base ont été migré vers le sélecteur du premier ennemi" -- WAS: PLUGINFIRSTENEMY_NOTIFY
L["SELECTOR_FIRSTENEMY_TITLE"] = "Premier ennemi" -- WAS: PLUGINFIRSTENEMY_TITLE
L["SCRIPT_EDITOR_RUN_BUTTON"] = "fonctionne" -- WAS: Run
L["SCRIPT_EDITOR_SAVE_SUCCESS"] = "Enregistré avec succès" -- WAS: Save success
L["SCRIPT_EDITOR_TEXTAREA_TITLE"] = "script" -- WAS: Script
-- DELETE: Script author = Nom de l'auteur
L["SCRIPT_EDITOR_TITLE"] = "Éditeur de script" -- WAS: Script editor
L["SCRIPT_MANAGER_TITLE"] = "Gestionnaire de scripts" -- WAS: Script manager
L["SCRIPT_EDITOR_NAME_TITLE"] = "Nom du script" -- WAS: Script name
-- DELETE: Script notes = Notes de script
L["SCRIPT_SELECTOR_TITLE"] = "Sélecteur de script" -- WAS: Script selector
L["SCRIPT_EDITOR_DELETE_SCRIPT_CONFIRMATION"] = "Êtes-vous sûr de vouloir supprimer le script  [% s-% s] ?" -- WAS: SCRIPT_EDITOR_DELETE_SCRIPT
L["SCRIPT_EDITOR_LABEL_TOGGLE_EXTRA"] = "Basculer l'éditeur d'informations étendu"
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_WARNING"] = "Un script existe déjà , la poursuite de l'importation écrasera le script actuel." -- WAS: SCRIPT_IMPORT_LABEL_COVER
L["SHARE_IMPORT_LABEL_EXTRA"] = "Continuer à importer des informations étendues" -- WAS: SCRIPT_IMPORT_LABEL_EXTRA
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_CHECKBOX"] = "Écraser et continuer l'importation" -- WAS: SCRIPT_IMPORT_LABEL_GOON
-- DELETE: SCRIPT_SELECTOR_LOST_TOOLTIP = 脚本选择器开发者没有定义 OnTooltipFormatting
-- DELETE: SCRIPT_SELECTOR_NOT_MATCH = Aucun script ne correspond à la bataille en cours
-- DELETE: SCRIPT_SELECTOR_NOTINSTALLED_HELP = Clic gauche pour voir, clic droit pour fermer
-- DELETE: SCRIPT_SELECTOR_NOTINSTALLED_TEXT = Un sélecteur de script utile n'a pas été installé
L["IN_BATTLE_SELECT_SCRIPT"] = "Sélectionnez le script" -- WAS: Select script
L["SCRIPT_MANAGER_TOGGLE"] = "Activer / désactiver le gestionnaire de scripts" -- WAS: TOGGLE_SCRIPT_MANAGER
L["SCRIPT_SELECTOR_TOGGLE"] = "Active/désactive le sélecteur de script" -- WAS: TOGGLE_SCRIPT_SELECTOR
L["TOOLTIP_CREATE_OR_DEBUG_SCRIPT"] = "Créer ou déboguer un script"
L["DATABASE_UPDATED_TO"] = "Mettre à jour vers la version :" -- WAS: UPDATED
