L = L or {}
L["SCRIPT_EDITOR_AUTOFORMAT_SCRIPT"] = "Script di Abbellimento" -- WAS: Beauty script
L["EDITOR_CREATE_SCRIPT"] = "Crea script" -- WAS: Create script
L["IN_BATTLE_DEBUGGING_SCRIPT"] = "Script di Debug" -- WAS: Debugging script
-- DELETE: DIALOG_COPY_URL_HELP = Premi Ctrl-C per copiare nel browser e per aprire
-- DELETE: Don't ask me = Niente più promemoria
-- DELETE: Download = Scarica
L["EDITOR_EDIT_SCRIPT"] = "Modifica lo script" -- WAS: Edit script
L["SHARE_EXPORT_SCRIPT"] = "Esporta" -- WAS: Export
L["OPTION_EDITOR_FONT_FACE"] = "Font" -- WAS: Font face
L["OPTION_EDITOR_FONT_SIZE"] = "Dimensione Font" -- WAS: Font size
L["SCRIPT_EDITOR_FOUND_ERROR"] = "Trovato Errore" -- WAS: Found error
L["SHARE_IMPORT_SCRIPT"] = "Importare" -- WAS: Import
L["SHARE_IMPORT_CHOOSE_KEY"] = "Seleziona un valore per chiudere..." -- WAS: IMPORT_CHOOSE_KEY
L["SHARE_IMPORT_CHOOSE_SELECTOR"] = "Seleziona un selettore di script..." -- WAS: IMPORT_CHOOSE_PLUGIN
L["SHARE_IMPORT_REINPUT_TEXT"] = "Ri-Modificare" -- WAS: IMPORT_REINPUT_TEXT
L["SHARE_IMPORT_SCRIPT_EXISTS"] = "lo script esiste già" -- WAS: IMPORT_SCRIPT_EXISTS
L["SHARE_IMPORT_SCRIPT_NOT_IMPORT_STRING_WARNING"] = "Hai inserito lo script, ti consigliamo di utilizzare il codice di condivisione per importare, ovviamente puoi continuare a importare." -- WAS: IMPORT_SCRIPT_WARNING
L["SHARE_IMPORT_SCRIPT_WELCOME"] = "Copia la stringa o lo script di condivisione nella casella di input." -- WAS: IMPORT_SCRIPT_WELCOME
L["SHARE_IMPORT_STRING_INCOMPLETE"] = "I dati della stringa condivisa sono incompleti. Ma può ancora essere importato." -- WAS: IMPORT_SHARED_STRING_WARNING
-- DELETE: Installed = Installato
L["DEFAULT_NEW_SCRIPT_NAME"] = "Nuovo Script" -- WAS: New script
L["IN_BATTLE_NO_SCRIPT"] = "Nessuno Script" -- WAS: No script
-- DELETE: Not Installed = Non Installato
-- DELETE: OPTION_GENERAL_NOTES = Ecco alcune impostazioni generali.
-- DELETE: OPTION_SCRIPTEDITOR_NOTES = Ecco le preferenze dell'editor di script
L["OPTION_SCRIPTSELECTOR_NOTES"] = "Qui puoi gestire se il selettore di script è abilitato e la priorità del selettore di script."
L["OPTION_AUTO_SELECT_SCRIPT_BY_ORDER"] = "Seleziona automaticamente gli script in base alla priorità del selettore di script" -- WAS: OPTION_SETTINGS_AUTO_SELECT_SCRIPT_BY_ORDER
L["OPTION_AUTO_SELECT_SCRIPT_ONLY_ONE"] = "Seleziona automaticamente quando è presente un solo script" -- WAS: OPTION_SETTINGS_AUTO_SELECT_SCRIPT_ONLY_ONE
L["OPTION_AUTOBUTTON_HOTKEY"] = "Tasti di scelta rapida automatici" -- WAS: OPTION_SETTINGS_AUTOBUTTON_HOTKEY
L["OPTION_HIDE_MINIMAP"] = "Nascondi l'icona della minimappa" -- WAS: OPTION_SETTINGS_HIDE_MINIMAP
L["OPTION_SETTINGS_HIDE_MINIMAP_TOOLTIP"] = "La modifica di questa impostazione richiede il ricaricamento dell'interfaccia utente. Continuare?"
L["OPTION_HIDE_SELECTOR_NO_SCRIPT"] = "Non mostrare il selettore di script quando non c'è uno script" -- WAS: OPTION_SETTINGS_HIDE_SELECTOR_NO_SCRIPT
L["OPTION_LOCK_SCRIPT_SELECTOR"] = "Blocca il selettore di script" -- WAS: OPTION_SETTINGS_LOCK_SCRIPT_SELECTOR
L["OPTION_NO_WAIT_DELETE_SCRIPT"] = "Non aspettare quando elimini gli script" -- WAS: OPTION_SETTINGS_NO_WAIT_DELETE_SCRIPT
L["OPTION_RESET_FRAMES"] = "Ripristina le dimensioni e la posizione del pannello" -- WAS: OPTION_SETTINGS_RESET_FRAMES
L["OPTION_TEST_BREAK"] = "Debug: il comando test interrompe lo script" -- WAS: OPTION_SETTINGS_TEST_BREAK
-- DELETE: Options = Opzioni
L["SELECTOR_ALLINONE_NOTES"] = "Tutte le battaglie pokemon possono usare questo script." -- WAS: PLUGINALLINONE_NOTES
L["SELECTOR_ALLINONE_TITLE"] = "Tutto in uno" -- WAS: PLUGINALLINONE_TITLE
L["SELECTOR_BASE_NOTES"] = "Questo selettore di script lega lo script alla formazione completa delle squadre avversarie." -- WAS: PLUGINBASE_NOTES
L["SELECTOR_BASE_ALLY"] = "La nostra formazione" -- WAS: PLUGINBASE_TEAM_ALLY
L["SELECTOR_BASE_ENEMY"] = "La formazione nemica" -- WAS: PLUGINBASE_TEAM_ENEMY
L["SELECTOR_BASE_TITLE"] = "Base" -- WAS: PLUGINBASE_TITLE
-- DELETE: PLUGINBASE_TOOLTIP_CREATE_SCRIPT = Nozioni di base: crea uno script per l'abbinamento corrente
L["SELECTOR_FIRSTENEMY_NOTES"] = "Questo selettore di script lega lo script al primo nemico della battaglia." -- WAS: PLUGINFIRSTENEMY_NOTES
L["DATABASE_UPDATE_BASE_TO_FIRSTENEMY_NOTIFICATION"] = "Si è riscontrato che hai già utilizzato la versione modificata di tdBattlePetScript e alcuni script della versione modificata del selettore Base sono stati migrati al selettore FirstEnemy." -- WAS: PLUGINFIRSTENEMY_NOTIFY
L["SELECTOR_FIRSTENEMY_TITLE"] = "Primo nemico" -- WAS: PLUGINFIRSTENEMY_TITLE
L["SCRIPT_EDITOR_RUN_BUTTON"] = "Avvia" -- WAS: Run
L["SCRIPT_EDITOR_SAVE_SUCCESS"] = "Salvato con successo" -- WAS: Save success
L["SCRIPT_EDITOR_TEXTAREA_TITLE"] = "Script" -- WAS: Script
-- DELETE: Script author = Nome dell'autore
L["SCRIPT_EDITOR_TITLE"] = "Editore di script" -- WAS: Script editor
L["SCRIPT_MANAGER_TITLE"] = "Gestore di Script" -- WAS: Script manager
L["SCRIPT_EDITOR_NAME_TITLE"] = "Nome dello Script" -- WAS: Script name
-- DELETE: Script notes = Note sullo Script
L["SCRIPT_SELECTOR_TITLE"] = "Selettore di script" -- WAS: Script selector
L["SCRIPT_EDITOR_DELETE_SCRIPT_CONFIRMATION"] = "Sei sicuro di voler |cffff0000cancella|r script |cffffd000[%s - %s]|r?" -- WAS: SCRIPT_EDITOR_DELETE_SCRIPT
L["SCRIPT_EDITOR_LABEL_TOGGLE_EXTRA"] = "Attiva/disattiva editor di informazioni sull'estensione"
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_WARNING"] = "Uno script esiste già in questa modalità di corrispondenza, continuare a importare sovrascriverà lo script corrente." -- WAS: SCRIPT_IMPORT_LABEL_COVER
L["SHARE_IMPORT_LABEL_EXTRA"] = "Continua a importare informazioni estese" -- WAS: SCRIPT_IMPORT_LABEL_EXTRA
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_CHECKBOX"] = "Sovrascrivi e continua a importare" -- WAS: SCRIPT_IMPORT_LABEL_GOON
-- DELETE: SCRIPT_SELECTOR_LOST_TOOLTIP = Lo sviluppatore del selettore di script non definisce OnTooltipFormatting
-- DELETE: SCRIPT_SELECTOR_NOT_MATCH = Nessun selettore di script corrisponde alla battaglia in corso
-- DELETE: SCRIPT_SELECTOR_NOTINSTALLED_HELP = Fare clic con il tasto sinistro per visualizzare, fare clic con il tasto destro per chiudere
-- DELETE: SCRIPT_SELECTOR_NOTINSTALLED_TEXT = Trovato un utile selettore di script non installato!
L["IN_BATTLE_SELECT_SCRIPT"] = "Seleziona script" -- WAS: Select script
L["SCRIPT_MANAGER_TOGGLE"] = "Attiva/disattiva gestione degli script" -- WAS: TOGGLE_SCRIPT_MANAGER
L["SCRIPT_SELECTOR_TOGGLE"] = "Attiva/disattiva il selettore di script" -- WAS: TOGGLE_SCRIPT_SELECTOR
L["TOOLTIP_CREATE_OR_DEBUG_SCRIPT"] = "Crea o esegui il debug di script"
L["DATABASE_UPDATED_TO"] = "Aggiorna alla versione:" -- WAS: UPDATED
