L = L or {}
L["IN_BATTLE_EXECUTE"] = "Автобой" -- WAS: Auto
L["SCRIPT_EDITOR_AUTOFORMAT_SCRIPT"] = "Отформатировать скрипт" -- WAS: Beauty script
L["EDITOR_CREATE_SCRIPT"] = "Создать скрипт" -- WAS: Create script
L["IN_BATTLE_DEBUGGING_SCRIPT"] = "Отладка скрипта" -- WAS: Debugging script
-- DELETE: DIALOG_COPY_URL_HELP = Нажмите Ctrl-C, чтобы скопировать в браузер, чтобы открыть
-- DELETE: Don't ask me = Не спрашивай меня
-- DELETE: Download = Загрузить
L["EDITOR_EDIT_SCRIPT"] = "Редактировать скрипт" -- WAS: Edit script
L["SHARE_EXPORT_SCRIPT"] = "Экспорт" -- WAS: Export
L["OPTION_EDITOR_FONT_FACE"] = "Шрифт" -- WAS: Font face
L["OPTION_EDITOR_FONT_SIZE"] = "Размер шрифта" -- WAS: Font size
L["SCRIPT_EDITOR_FOUND_ERROR"] = "Найдена ошибка" -- WAS: Found error
L["SHARE_IMPORT_SCRIPT"] = "Импорт" -- WAS: Import
L["SHARE_IMPORT_CHOOSE_KEY"] = "Пожалуйста, выберите значение \"закрыть\"..." -- WAS: IMPORT_CHOOSE_KEY
L["SHARE_IMPORT_CHOOSE_SELECTOR"] = "Выберите селектор сценариев..." -- WAS: IMPORT_CHOOSE_PLUGIN
L["SHARE_IMPORT_REINPUT_TEXT"] = "Повторное редактирование" -- WAS: IMPORT_REINPUT_TEXT
L["SHARE_IMPORT_SCRIPT_EXISTS"] = "Сценарий уже существует" -- WAS: IMPORT_SCRIPT_EXISTS
L["SHARE_IMPORT_SCRIPT_NOT_IMPORT_STRING_WARNING"] = "Вы ввели сценарий, который предлагает вам использовать импорт кода обмена, и, конечно же, вы можете продолжить импорт." -- WAS: IMPORT_SCRIPT_WARNING
L["SHARE_IMPORT_SCRIPT_WELCOME"] = "Скопируйте общую строку или скрипт в поле ввода." -- WAS: IMPORT_SCRIPT_WELCOME
L["SHARE_IMPORT_STRING_INCOMPLETE"] = "Совместное использование строковых данных не является полным. Но все равно можно импортировать." -- WAS: IMPORT_SHARED_STRING_WARNING
-- DELETE: Installed = Установленный
L["DEFAULT_NEW_SCRIPT_NAME"] = "Новый скрипт" -- WAS: New script
L["DIRECTOR_TEST_NEXT_ACTION"] = "Следующее действие" -- WAS: NEXT_ACTION
L["IN_BATTLE_NO_SCRIPT"] = "Нет скрипта" -- WAS: No script
L["SELECTOR_REMATCH_NO_TEAM_FOR_SCRIPT"] = "Ни одна команда не соответствует этому сценарию" -- WAS: NO_TEAM_FOR_SCRIPT
-- DELETE: Not Installed = Неустановленный
L["SELECTOR_REMATCH_NOTES"] = "Этот селектор скриптов будет привязан к команде Rematch." -- WAS: NOTES
-- DELETE: OPTION_GENERAL_NOTES = Общие настройки.
-- DELETE: OPTION_SCRIPTEDITOR_NOTES = Настройки редактора скриптов
L["OPTION_SCRIPTSELECTOR_NOTES"] = "Настройки селекторов скриптов"
L["OPTION_AUTO_SELECT_SCRIPT_BY_ORDER"] = "Автоматически выбирает сценарий на основе приоритета селектора сценариев" -- WAS: OPTION_SETTINGS_AUTO_SELECT_SCRIPT_BY_ORDER
L["OPTION_AUTO_SELECT_SCRIPT_ONLY_ONE"] = "Автоматически выбирать, когда есть только один скрипт." -- WAS: OPTION_SETTINGS_AUTO_SELECT_SCRIPT_ONLY_ONE
L["OPTION_AUTOBUTTON_HOTKEY"] = "Назначение автоматической кнопки." -- WAS: OPTION_SETTINGS_AUTOBUTTON_HOTKEY
L["OPTION_HIDE_MINIMAP"] = "Скрыть иконку у миникарты" -- WAS: OPTION_SETTINGS_HIDE_MINIMAP
L["OPTION_SETTINGS_HIDE_MINIMAP_TOOLTIP"] = "Обнаружена модификация \"MinimapButtonBag\", для изменения настройки необходимо перезагрузить интерфейс. Сделать это?"
L["OPTION_HIDE_SELECTOR_NO_SCRIPT"] = "Не показывать, если нет скриптов." -- WAS: OPTION_SETTINGS_HIDE_SELECTOR_NO_SCRIPT
L["OPTION_LOCK_SCRIPT_SELECTOR"] = "Блокировка селектора сценариев" -- WAS: OPTION_SETTINGS_LOCK_SCRIPT_SELECTOR
L["OPTION_NO_WAIT_DELETE_SCRIPT"] = "Не ждать перед удалением." -- WAS: OPTION_SETTINGS_NO_WAIT_DELETE_SCRIPT
L["OPTION_NOTIFY_BUTTON_ACTIVE"] = "Воспроизведение звука, когда кнопка \"Автобой\" становится активной" -- WAS: OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE
L["OPTION_NOTIFY_BUTTON_ACTIVE_SOUND"] = "Звук" -- WAS: OPTION_SETTINGS_NOTIFY_BUTTON_ACTIVE_SOUND
L["OPTION_RESET_FRAMES"] = "Сброс размера и положения панели" -- WAS: OPTION_SETTINGS_RESET_FRAMES
L["OPTION_TEST_BREAK"] = "Отладка: скрипт проверки тестового сценария." -- WAS: OPTION_SETTINGS_TEST_BREAK
-- DELETE: Options = Опции
L["SELECTOR_ALLINONE_NOTES"] = "Все битвы питомцев доступны с помощью этого скрипта." -- WAS: PLUGINALLINONE_NOTES
L["SELECTOR_ALLINONE_TITLE"] = "Все в одном" -- WAS: PLUGINALLINONE_TITLE
L["SELECTOR_BASE_NOTES"] = "Базовый селектор выбирает обе стороны" -- WAS: PLUGINBASE_NOTES
L["SELECTOR_BASE_ALLY"] = "Друг" -- WAS: PLUGINBASE_TEAM_ALLY
L["SELECTOR_BASE_ENEMY"] = "Враг" -- WAS: PLUGINBASE_TEAM_ENEMY
L["SELECTOR_BASE_TITLE"] = "Базовый" -- WAS: PLUGINBASE_TITLE
-- DELETE: PLUGINBASE_TOOLTIP_CREATE_SCRIPT = Базовый: Создание сценария для текущей битвы.
L["SELECTOR_FIRSTENEMY_NOTES"] = "Этот селектор сценариев привязывает скрипт к первому врагу в битве." -- WAS: PLUGINFIRSTENEMY_NOTES
L["DATABASE_UPDATE_BASE_TO_FIRSTENEMY_NOTIFICATION"] = "Обнаружив, что вы ранее использовали модифицированную версию tdBattlePetScript, мы перенесли часть скрипта измененной версии базового селектора в селектор FirstEnemy." -- WAS: PLUGINFIRSTENEMY_NOTIFY
L["SELECTOR_FIRSTENEMY_TITLE"] = "Первый Враг" -- WAS: PLUGINFIRSTENEMY_TITLE
L["SCRIPT_EDITOR_RUN_BUTTON"] = "Запуск" -- WAS: Run
L["SCRIPT_EDITOR_SAVE_SUCCESS"] = "Сохранено" -- WAS: Save success
L["SCRIPT_EDITOR_TEXTAREA_TITLE"] = "Скрипт" -- WAS: Script
-- DELETE: Script author = Автор скрипта
L["SCRIPT_EDITOR_TITLE"] = "Редактор скриптов" -- WAS: Script editor
L["SCRIPT_MANAGER_TITLE"] = "Менеджер скриптов" -- WAS: Script manager
L["SCRIPT_EDITOR_NAME_TITLE"] = "Имя скрипта" -- WAS: Script name
-- DELETE: Script notes = Примечания к скрипту
L["SCRIPT_SELECTOR_TITLE"] = "Селектор скриптов" -- WAS: Script selector
L["SCRIPT_EDITOR_DELETE_SCRIPT_CONFIRMATION"] = "Вы действительно хотите |cffff0000удалить|r скрипт |cffffd000[%s - %s]|r ?" -- WAS: SCRIPT_EDITOR_DELETE_SCRIPT
L["SCRIPT_EDITOR_LABEL_TOGGLE_EXTRA"] = "Дополнительная информация"
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_WARNING"] = "Сценарий уже существует, если вы продолжите - предыдущий сценарий будет перезаписан импортируемым скриптом" -- WAS: SCRIPT_IMPORT_LABEL_COVER
L["SHARE_IMPORT_LABEL_EXTRA"] = "Продолжить с расширенной информацией." -- WAS: SCRIPT_IMPORT_LABEL_EXTRA
L["SHARE_IMPORT_LABEL_ALREADY_EXISTS_CHECKBOX"] = "Продолжить с перезаписью." -- WAS: SCRIPT_IMPORT_LABEL_GOON
-- DELETE: SCRIPT_SELECTOR_LOST_TOOLTIP = Разработчик селектора скриптов не определил функцию \"OnTooltipFormatting\"
-- DELETE: SCRIPT_SELECTOR_NOT_MATCH = Нет селектора скриптов для текущей битвы.
-- DELETE: SCRIPT_SELECTOR_NOTINSTALLED_HELP = ЛКМ для просмотра, ПКМ для закрытия
-- DELETE: SCRIPT_SELECTOR_NOTINSTALLED_TEXT = Найден полезный селектор сценариев, который не установлен!
L["IN_BATTLE_SELECT_SCRIPT"] = "Выбор скрипта." -- WAS: Select script
L["SCRIPT_MANAGER_TOGGLE"] = "Показать менеджер скриптов" -- WAS: TOGGLE_SCRIPT_MANAGER
L["SCRIPT_SELECTOR_TOGGLE"] = "Показать селектор скриптов" -- WAS: TOGGLE_SCRIPT_SELECTOR
L["TOOLTIP_CREATE_OR_DEBUG_SCRIPT"] = "Создание или отладка скрипта."
L["DATABASE_UPDATED_TO"] = "Обновление до версии" -- WAS: UPDATED
-- DELETE: WRITE_SCRIPT = Написать сценарий
